# Generated by Django 5.1 on 2024-09-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='search',
            new_name='public',
        ),
    ]
